import type { ActivityEventType, ActivityModule } from './activity-log.entity.js';

export const ACTIVITY_EVENT_TYPES = [
  'AUTHENTICATION',
  'COMPANY',
  'EMPLOYEE',
  'ORGANIZATION',
  'TRANSACTION',
  'TRIP',
  'EXPENSE',
  'WORKFORCE',
  'TRACKING',
] as const satisfies readonly ActivityEventType[];

export const ACTIVITY_MODULES = [
  'auth',
  'company',
  'employee',
  'branch',
  'warehouse',
  'vehicle',
  'transaction',
  'trip',
  'expense',
  'attendance',
  'leave',
  'cash-advance',
  'payroll',
  'user',
  'tracking',
] as const satisfies readonly ActivityModule[];

export const ACTIVITY_ACTIONS = {
  AUTH_LOGIN: 'auth.login',
  AUTH_ADMIN_LOGIN: 'auth.admin_login',
  AUTH_LOGOUT: 'auth.logout',
  PASSWORD_CHANGED: 'user.password_changed',
  PASSWORD_ADMIN_RESET: 'user.password_admin_reset',
  COMPANY_UPDATED: 'company.updated',
  EMPLOYEE_CREATED: 'employee.created',
  EMPLOYEE_UPDATED: 'employee.updated',
  EMPLOYEE_ARCHIVED: 'employee.archived',
  EMPLOYEE_ACCOUNT_CREATED: 'employee.account_created',
  EMPLOYEE_ACCOUNT_DISABLED: 'employee.system_access_disabled',
  BRANCH_CREATED: 'branch.created',
  WAREHOUSE_CREATED: 'warehouse.created',
  VEHICLE_CREATED: 'vehicle.created',
  VEHICLE_UPDATED: 'vehicle.updated',
  TRANSACTION_CREATED: 'transaction.created',
  TRANSACTION_UPDATED: 'transaction.updated',
  TRANSACTION_SUBMITTED: 'transaction.finished',
  TRANSACTION_RETURNED_TO_DRAFT: 'transaction.returned_to_draft',
  TRANSACTION_PAID: 'transaction.settled',
  TRANSACTION_CANCELLED: 'transaction.cancelled',
  TRIP_CREATED: 'trip.created',
  TRIP_STARTED: 'trip.started',
  TRIP_COMPLETED: 'trip.completed',
  TRIP_CANCELLED: 'trip.cancelled',
  TRIP_LOAD_ENABLED: 'trip.load_enabled',
  TRIP_LOAD_DISABLED: 'trip.load_disabled',
  TRIP_LOAD_CREATED: 'trip.load_created',
  TRIP_LOAD_UPDATED: 'trip.load_updated',
  TRIP_LOAD_DELETED: 'trip.load_deleted',
  TRIP_LOAD_ITEM_ADDED: 'trip.load_item_added',
  TRIP_LOAD_ITEM_UPDATED: 'trip.load_item_updated',
  TRIP_LOAD_ITEM_REMOVED: 'trip.load_item_removed',
  EXPENSE_CREATED: 'expense.created',
  EXPENSE_RECORDED: 'expense.recorded',
  EXPENSE_CANCELLED: 'expense.cancelled',
  ATTENDANCE_TIME_IN: 'attendance.time_in',
  ATTENDANCE_TIME_OUT: 'attendance.time_out',
  LEAVE_RECORDED: 'leave.recorded',
  CASH_ADVANCE_CREATED: 'cash_advance.created',
  PAYROLL_PAID: 'payroll.paid',
  SUBSCRIPTION_CREATED: 'subscription.created',
  SUBSCRIPTION_RENEWED: 'subscription.renewed',
  SUBSCRIPTION_UPDATED: 'subscription.updated',
  SUBSCRIPTION_EXPIRED: 'subscription.expired',
  SUBSCRIPTION_SUSPENDED: 'subscription.suspended',
  SUBSCRIPTION_REACTIVATED: 'subscription.reactivated',
  TRACKING_STARTED: 'tracking.started',
  TRACKING_STOPPED: 'tracking.stopped',
  ADMIN_COMPANY_CREATED: 'admin.company_created',
  ADMIN_ACCOUNT_CREATED: 'admin.account_created',
} as const;
